version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    expose:
      - "80"
    volumes:
      - ./db:/db
      - ./log/gunicorn:/log/gunicorn
      - ./log/sqlite:/log/sqlite
    environment:
      - SQLITE_DBFILE=/db/sqlite.db
      - SQLITE_LOGFILE=/log/sqlite/info.log
      - GUNICORN_ACCESS_LOGFILE=/log/gunicorn/access.log
      - GUNICORN_DEBUG_LOGFILE=/log/gunicorn/debug.log
      - GUNICORN_WORKERS=2
      - GUNICORN_WORKER_CONNECTIONS=300
      - GUNICORN_PORT=80
    restart: unless-stopped
