version: "3"

services:
  app:
    image: python:3.11-slim-bookworm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/flask-htmx/app
      - ./db:/flask-htmx/db
      - ./log/gunicorn:/flask-htmx/log/gunicorn
      - ./log/sqlite:/flask-htmx/log/sqlite
      - ./appenv:/flask-htmx/appenv
      - ./scripts:/flask-htmx/scripts
    env_file:
      - ./.env
    restart: on-failure:5
    command: ["/flask-htmx/scripts/at-docker-init.sh"]
