version: "3"

services:
  app:
    build: .
    image: flask-htmx
    ports:
      - "8080:8080"
    volumes:
      - db:/db
    tmpfs:
      - /log:rw,noatime
    environment:
      - SQLITE_DBFILE="/db/sqlite.db"
      - SQLITE_LOGFILE="/log/sqlite.log"
      - GUNICORN_ACCESS_LOGFILE="/log/gunicorn-access.log"
      - GUNICORN_DEBUG_LOGFILE="/log/gunicorn-debug.log"
